import { Colors } from "../utils/colors";

export const jobDetailsStyles = {
  formSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    width: 600,
    paddingTop: 20,
    paddingLeft: 28,
    paddingRight: 28,
    paddingBottom: 28,
    borderRadius: 20,
    boxShadow: "0px 0px 20px rgba(0,0,0,0.1)",
  },
  inputSection: {
    display: "flex",
    flexDirection: "column",
    paddingBottom: 10,
    width: "100%",
  },
  inputDesc: {
    marginTop: 20,
    marginBottom: 10,
    fontSize: 16,
    fontWeight: 600,
    color: Colors.tundora,
  },
  inputTextfield: {
    fontSize: 16,
    outline: "none",
    borderStyle: "solid",
    borderColor: Colors.alto,
    borderWidth: 1,
    borderRadius: 3,
    height: 32,
    width: "100%",
    paddingLeft: 10,
  },
  nextStepButton: {
    outline: "none",
    border: "none",
    height: 38,
    marginTop: 17,
    color: Colors.white,
    backgroundColor: Colors.blue,
    fontWeight: 600,
    fontSize: 16,
    cursor: "pointer",
    borderRadius: 12,
    paddingLeft: 15,
    paddingRight: 15,
    width: 200,
  },
  submitSection: {
    display: "flex",
    flexDirection: "column",
  },
  title: {
    fontSize: 32,
    fontWeight: 600,
    textAlign: "center",
  },
  outerContainer: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    padding: 45,
    alignItems: "center",
    flex: 1,
  },
  checkBoxContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "column",
    width: "100%",
    marginBottom: 14,
    marginTop: 15,
  },
  checkBox: {
    marginTop: 20,
    marginBottom: 10,
    marginRight: 10,
    cursor: "pointer",
  },
  realMoneyWarning: {
    color: Colors.warningYellow,
  },
  largerTitle: {
    fontSize: 32,
    color: Colors.tundora,
    fontWeight: 600,
    marginBottom: 30,
  },
  smallDesc: {
    fontSize: 16,
    color: Colors.tundora,
  },
  defaultBehaviorText: {
    color: Colors.darkGray1,
    marginTop: -2,
  },
  sequence: {
    display: "flex",
    flexDirection: "row",
  },
};
